cloud:
  aws:
    credentials:
      access-key: AKIATGAUJMJBHVBJLWPD
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: pss-papi-store-online-storage


#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB